# Generated by Django 5.2.5 on 2025-09-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_imagesetting_options_imagesetting_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesetting',
            options={'verbose_name': 'Image Setting', 'verbose_name_plural': 'Image Settings'},
        ),
    ]
