# Generated by Django 5.2.5 on 2025-09-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_skill_alter_generalsetting_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
