# Generated by Django 5.2.5 on 2025-09-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_skill_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
