# Generated by Django 5.2.5 on 2025-09-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='major',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Degree'),
        ),
    ]
