# Generated by Django 5.2.5 on 2025-10-16 18:06

import resume.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default='', storage=resume.custom_storages.DocumentStorage(), upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', storage=resume.custom_storages.ImageSettingStorage(), upload_to='', verbose_name='Image'),
        ),
    ]
